name: Run Spotify Rotation

on:
  workflow_dispatch:      # Allow manual triggering
  schedule:
    - cron: '0 0 * * 5'   # Weekly at midnight on Friday
      timezone: 'America/New_York'

jobs:
  create-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install
        
      - name: Run script
        env:
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          
        run: npm start -- -u "30 / 30" -l 30 -t short